-- Insert data into the provinces table
INSERT INTO provinces (name, description, image) VALUES
('Abra', 'Abra is a rugged, landlocked province nestled in the northwestern part of the Cordillera region. Surrounded by the Ilocos Region and the rest of the Cordilleras, it is characterized by wide river valleys and lush mountains. Abra is home to the Itneg (Tingguian) people, whose rich traditions in weaving, tattooing, and indigenous rituals persist today. The province also bears Spanish colonial influences, evident in centuries-old churches and ancestral homes in the capital, Bangued. Agriculture is the backbone of Abra’s economy, with rice, corn, and tobacco being the main crops.', 'abra.jpg'),
('Albay', 'Albay is renowned for the majestic Mayon Volcano, a natural wonder celebrated for its perfect cone shape and a UNESCO Global Geopark candidate. The province offers a mix of adventure and culture, with attractions like the Cagsawa Ruins, a historical site from the 1814 eruption, and the annual Magayon Festival celebrating Bicolano heritage. Albay’s capital, Legazpi City, serves as the regional center, blending urban development with scenic views of the volcano. Its coastal location along the Albay Gulf also makes it a gateway to marine adventures like whale shark watching.', 'albay.jpg'),
('Apayao', 'Apayao lies at the northern tip of CAR, bordered by Cagayan and Ilocos Norte. It is known for its dense tropical forests, abundant wildlife, and winding rivers like the Apayao and Abulug Rivers. Apayao is one of the least densely populated provinces, allowing much of its natural landscape to remain pristine. The Isnag people are the indigenous inhabitants, and they maintain strong ties to their ancestral lands and traditional governance systems. Apayao has also been identified as a key biodiversity area and a promising ecotourism destination.', 'apayao.jpg'),
('Aurora', 'Aurora is a coastal province in the eastern region of Central Luzon, bordering the Philippine Sea. It is defined by its mountainous terrain, with the Sierra Madre mountain range occupying most of its territory. The province is famous for its natural wonders, such as unspoiled beaches, waterfalls, and forests. The provincial capital, Baler, is renowned for its surfing sites and historical sites. The economy of Aurora relies mainly on agriculture, fishing, and eco-tourism.', 'aurora.jpg'),
('Bataan', 'Bataan is a province located on Central Luzon''s western side, bordering the South China Sea and Manila Bay. It is also known for its historical past with the Bataan Death March of World War II. It has evolved to become an industrial center where economic zones and manufacturing plants are located. Natural attractions in Bataan are beaches, mountains, and heritage sites. Balanga City is the capital of the province and is a hub for education and trade.', 'bataan.jpg'),
('Batangas', 'Batangas is a province celebrated for its stunning coastal landscapes, offering popular beaches and world-class diving spots, along with a rich historical heritage marked by the iconic Taal Volcano and the preserved Taal Heritage Town; its economy is driven by a mix of agriculture, particularly sugarcane and coffee production, and industry, with Batangas City serving as a vital port and industrial hub.', 'batangas.jpg'),
('Benguet', 'Benguet is a mountainous province located in the southernmost part of CAR. It surrounds Baguio City, which was carved out from its territory. Benguet’s cool climate and high elevation make it ideal for cultivating temperate crops, earning it the nickname "Salad Bowl of the Philippines." The province is home to the Ibaloi and Kankanaey ethnolinguistic groups, known for their rich oral traditions and sustainable farming practices. Historically, Benguet was also a mining hub, especially for gold and copper. La Trinidad, the capital, is famous for its strawberry farms and flower gardens.', 'benguet.jpg'),
('Bulacan', 'Bulacan is the most culturally and historically affluent province in the Philippines, situated north of Metro Manila. It was a key province during the Philippine Revolution and the site of the historic Barasoain Church. The province has a thriving economy, with commerce, industry, and education centers. Bulacan also has lively festivals and crafts like jewelry-making, embroidery, and pyrotechnics. While urbanized, it still has a lot of green and agricultural areas, hence a mix of tradition and modernity.', 'bulacan.jpg'),
('Cagayan', 'Cagayan is an eastern coastal province in Luzon, famous for its rich heritage, agricultural resources, and longest river in the country, Cagayan. It is an entry point for the Babuyan Islands, and it''s where the Callao Cave, among other wonders of nature, is located. The economy depends mainly on farming, which exports rice, corn, and tobacco. Cagayan also experiences a developing tourist industry, complemented by places of historical sites and natural resources.', 'cagayan.jpg'),
('Camarines Norte', 'Camarines Norte is a coastal province famous for its pristine beaches, particularly the Calaguas Islands, a group of white-sand islands attracting tourists seeking unspoiled nature. The province is also known for its historical sites, such as the centuries-old churches in Daet, its capital, reflecting Spanish colonial influence. It serves as a northern gateway to the Bicol Region, with a landscape that includes rugged mountains and fertile plains ideal for agriculture. Camarines Norte’s proximity to Quezon province has fostered a blend of Tagalog and Bicolano cultures.', 'camarines_norte.jpg');

-- Insert data into the languages table
INSERT INTO languages (name) VALUES
('Ilocano'), ('Tingguian'), ('Tagalog'), ('English'), ('Bicolano'), ('Kapampangan'), ('Batangueño'), ('Kankanaey'), ('Ibaloi'), ('Isnag'), ('Malaueg'), ('Kalanguya'), ('Bontoc'), ('Manide'), ('Rinconada Bikol'), ('Central Bikol'), ('Ivatan'), ('Cuyonon'), ('Hiligaynon'), ('Kinaray-a'), ('Palawano'), ('Masbateño'), ('Cebuano'), ('Romblomanon'), ('Onhan'), ('Asi'), ('Sambal'), ('Gaddang'), ('Pangasinan'), ('Bisaya'), ('Chavacano'), ('Tuwali'), ('Ayangan'), ('Sinadanga'), ('Balangao'), ('Applai'), ('Baliwon');

-- Insert data into the province_languages table
INSERT INTO province_languages (province_id, language_id, percentage) VALUES
(1, 1, 15.0), (1, 2, 75.0), (1, 3, 5.0), (1, 4, 5.0),
(2, 5, 85.0), (2, 3, 10.0), (2, 4, 3.0), (2, 6, 2.0),
(3, 10, 27.5), (3, 1, 61.2), (3, 3, 1.2), (3, 11, 3.7), (3, 12, 2.4),
(4, 3, 70.7), (4, 1, 26.1), (4, 5, 0.8), (4, 6, 2.4),
(5, 3, 97.0), (5, 6, 1.7), (5, 1, 0.4), (5, 6, 0.9),
(6, 3, 95.0), (6, 7, 4.0), (6, 4, 1.0),
(7, 8, 36.3), (7, 1, 33.9), (7, 9, 16.5), (7, 3, 7.3), (7, 12, 2.9), (7, 6, 3.1);